//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5483
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace SaGE.Correspondence.Domain
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class EmailMeta
    {
        private string toAddressField;

        private string fromAddressField;

        private string fromAddressFriendlyField;

        private string templateField;

        private string bccField;

        private string subjectField;

        private string pDFField;

        private string pDFFriendlyField;

        private string nPSField;

        private EmailXHeader[] xHeaderField;

        private EmailAttachment[] attachmentField;

        private EmailSearchReplace[] searchReplaceField;

        /// <remarks/>
        public string ToAddress
        {
            get { return this.toAddressField; }
            set { this.toAddressField = value; }
        }

        /// <remarks/>
        public string FromAddress
        {
            get { return this.fromAddressField; }
            set { this.fromAddressField = value; }
        }

        public string FromAddressFriendly
        {
            get { return this.fromAddressFriendlyField; }
            set { this.fromAddressFriendlyField = value; }
        }
        
        /// <remarks/>
        public string Bcc
        {
            get { return this.bccField; }
            set { this.bccField = value; }
        }

        /// <remarks/>
        public string Template
        {
            get { return this.templateField; }
            set { this.templateField = value; }
        }

        /// <remarks/>
        public string Subject
        {
            get { return this.subjectField; }
            set { this.subjectField = value; }
        }

        /// <remarks/>
        public string PDF
        {
            get { return this.pDFField; }
            set { this.pDFField = value; }
        }

        public string PDFFriendly
        {
            get { return this.pDFFriendlyField; }
            set { this.pDFFriendlyField = value; }
        }

        /// <remarks/>
        public string NPS
        {
            get { return this.nPSField; }
            set { this.nPSField = value; }
        }

        /// <remarks/>
        [XmlElement("XHeader")]
        public EmailXHeader[] XHeader
        {
            get { return this.xHeaderField; }
            set { this.xHeaderField = value; }
        }

        /// <remarks/>
        [XmlElement("Attachment")]
        public EmailAttachment[] Attachment
        {
            get { return this.attachmentField; }
            set { this.attachmentField = value; }
        }

        /// <remarks/>
        [XmlElement("SearchReplace")]
        public EmailSearchReplace[] SearchReplace
        {
            get { return this.searchReplaceField; }
            set { this.searchReplaceField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public partial class EmailXHeader
    {
        private string tagField;

        private string valueField;

        /// <remarks/>
        public string Tag
        {
            get { return this.tagField; }
            set { this.tagField = value; }
        }

        /// <remarks/>
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public partial class EmailAttachment
    {
        private string pathField;

        private string nameField;

        /// <remarks/>
        public string Path
        {
            get { return this.pathField; }
            set { this.pathField = value; }
        }

        /// <remarks/>
        public string Name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public partial class EmailSearchReplace
    {

        private string tagField;

        private string valueField;

        /// <remarks/>
        public string Tag
        {
            get { return this.tagField; }
            set { this.tagField = value; }
        }

        /// <remarks/>
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
             
    }
}